"""
setup_8values.py

Create (on the MAIN database, config/db_config.json) the tables for the 8values
LLM survey pipeline, and seed the reference data.

Tables
------
  eightvalues_question        70 quiz statements + per-axis effect weights (seeded
                              from config/eightvalues_questions.json).
  eightvalues_answer_option   the 5 Likert options + multipliers (Strongly Agree
                              +1.0 ... Strongly Disagree -1.0).
  eightvalues_probe_statement per question, a 'for' and 'against' statement used
                              to probe whether a model will swing to both extremes
                              (seeded from config/eightvalues_probe_statements.json
                              if present).
  transcript_chunk_table      transcript chunks + embeddings (DOUBLE PRECISION[])
                              for RAG retrieval. vid_id -> vid_table.id.
  eightvalues_run             one row per survey run == one task. mode is
                              transcript / baseline / probe_for / probe_against.
                              vid_id is NULL for baseline/probe. Doubles as the
                              work queue (status pending/in_progress/done/error).
  eightvalues_response        one row per question within a run (chosen answer,
                              or failed + raw output; keeps every attempt).
  eightvalues_score           per-run 4-axis 0-100 scores (+ raw sums / maxes).

No pgvector needed: embeddings are stored as float arrays and similarity is done
in the runner (each video has only a few chunks).

Usage:
    python setup_8values.py                 # create tables + seed reference data
    python setup_8values.py --no-seed       # tables only
    python setup_8values.py --drop          # DROP and recreate (destroys 8values data)
"""

import argparse
import json
import os

import psycopg2

ROOT = os.path.dirname(os.path.abspath(__file__))
QUESTIONS_PATH = os.path.join(ROOT, "config", "eightvalues_questions.json")
PROBE_PATH = os.path.join(ROOT, "config", "eightvalues_probe_statements.json")

# Embedding dimension for the chunk store is not fixed in the schema (float[] is
# variable-length); the runner records which embedding_model produced each chunk.


def load_db_config():
    with open(os.path.join(ROOT, "config", "db_config.json"), "r") as f:
        return json.load(f)


DDL = """
CREATE TABLE IF NOT EXISTS eightvalues_question (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_index    INTEGER NOT NULL UNIQUE,
    question_text TEXT NOT NULL,
    effect_econ   SMALLINT NOT NULL DEFAULT 0,
    effect_dipl   SMALLINT NOT NULL DEFAULT 0,
    effect_govt   SMALLINT NOT NULL DEFAULT 0,
    effect_scty   SMALLINT NOT NULL DEFAULT 0,
    insert_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS eightvalues_answer_option (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sort_order SMALLINT NOT NULL UNIQUE,        -- 1..5, the "answer index"
    label      VARCHAR(40) NOT NULL UNIQUE,
    multiplier NUMERIC(4,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS eightvalues_probe_statement (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id    BIGINT NOT NULL REFERENCES eightvalues_question (id) ON DELETE CASCADE,
    direction      VARCHAR(8) NOT NULL CHECK (direction IN ('for', 'against')),
    statement_text TEXT NOT NULL,
    insert_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (question_id, direction)
);

CREATE TABLE IF NOT EXISTS transcript_chunk_table (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vid_id          BIGINT NOT NULL REFERENCES vid_table (id),
    chunk_index     INTEGER NOT NULL,
    text            TEXT NOT NULL,
    token_count     INTEGER,
    embedding       DOUBLE PRECISION[] NOT NULL,
    embedding_model VARCHAR(128) NOT NULL,
    insert_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (vid_id, chunk_index)
);
CREATE INDEX IF NOT EXISTS idx_transcript_chunk_vid ON transcript_chunk_table (vid_id);

CREATE TABLE IF NOT EXISTS eightvalues_run (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mode            VARCHAR(16) NOT NULL
                    CHECK (mode IN ('transcript', 'baseline', 'probe_for', 'probe_against')),
    vid_id          BIGINT REFERENCES vid_table (id),   -- NULL for baseline/probe
    llm_model       VARCHAR(128) NOT NULL,
    repeat_index    INTEGER NOT NULL,
    embedding_model VARCHAR(128),                       -- retrieval embeddings (transcript mode)
    top_k           INTEGER,
    temperature     NUMERIC(4,2),
    status          VARCHAR(12) NOT NULL DEFAULT 'pending',  -- pending/in_progress/done/error
    attempts        INTEGER NOT NULL DEFAULT 0,
    failed_count    INTEGER NOT NULL DEFAULT 0,          -- # questions that couldn't be answered
    error           TEXT,
    claimed_at      TIMESTAMP,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- One run per (mode, video, model, repeat). vid_id is NULL for baseline/probe,
-- so COALESCE to a sentinel to keep the uniqueness meaningful.
CREATE UNIQUE INDEX IF NOT EXISTS uq_eightvalues_run
    ON eightvalues_run (mode, COALESCE(vid_id, -1), llm_model, repeat_index);
CREATE INDEX IF NOT EXISTS idx_eightvalues_run_status ON eightvalues_run (status);

CREATE TABLE IF NOT EXISTS eightvalues_response (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id           BIGINT NOT NULL REFERENCES eightvalues_run (id) ON DELETE CASCADE,
    question_id      BIGINT NOT NULL REFERENCES eightvalues_question (id),
    answer_option_id BIGINT REFERENCES eightvalues_answer_option (id),  -- NULL if failed
    failed           BOOLEAN NOT NULL DEFAULT FALSE,
    attempts         INTEGER NOT NULL DEFAULT 1,
    confidence       NUMERIC(5,4),
    reason           TEXT,
    raw_output       TEXT,                  -- final raw LLM text
    all_outputs      JSONB,                 -- every attempt's raw text, for review
    insert_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (run_id, question_id)
);
CREATE INDEX IF NOT EXISTS idx_eightvalues_response_run ON eightvalues_response (run_id);

CREATE TABLE IF NOT EXISTS eightvalues_score (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id         BIGINT NOT NULL UNIQUE REFERENCES eightvalues_run (id) ON DELETE CASCADE,
    score_econ     NUMERIC(7,3),   -- 0..100 (0 = one pole, 100 = the other)
    score_dipl     NUMERIC(7,3),
    score_govt     NUMERIC(7,3),
    score_scty     NUMERIC(7,3),
    raw_econ       NUMERIC(10,3),
    raw_dipl       NUMERIC(10,3),
    raw_govt       NUMERIC(10,3),
    raw_scty       NUMERIC(10,3),
    max_econ       NUMERIC(10,3),
    max_dipl       NUMERIC(10,3),
    max_govt       NUMERIC(10,3),
    max_scty       NUMERIC(10,3),
    answered_count INTEGER,
    failed_count   INTEGER,
    insert_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""

DROP = """
DROP TABLE IF EXISTS eightvalues_score CASCADE;
DROP TABLE IF EXISTS eightvalues_response CASCADE;
DROP TABLE IF EXISTS eightvalues_run CASCADE;
DROP TABLE IF EXISTS transcript_chunk_table CASCADE;
DROP TABLE IF EXISTS eightvalues_probe_statement CASCADE;
DROP TABLE IF EXISTS eightvalues_answer_option CASCADE;
DROP TABLE IF EXISTS eightvalues_question CASCADE;
"""

ANSWER_OPTIONS = [
    (1, "Strongly Agree", 1.0),
    (2, "Agree", 0.5),
    (3, "Neutral/Unsure", 0.0),
    (4, "Disagree", -0.5),
    (5, "Strongly Disagree", -1.0),
]


def seed_answer_options(cur):
    for sort_order, label, mult in ANSWER_OPTIONS:
        cur.execute(
            """
            INSERT INTO eightvalues_answer_option (sort_order, label, multiplier)
            VALUES (%s, %s, %s)
            ON CONFLICT (sort_order) DO UPDATE SET label = EXCLUDED.label, multiplier = EXCLUDED.multiplier
            """,
            (sort_order, label, mult),
        )


def seed_questions(cur):
    with open(QUESTIONS_PATH, "r", encoding="utf-8") as f:
        questions = json.load(f)
    for idx, item in enumerate(questions):
        eff = item.get("effect") or {}
        cur.execute(
            """
            INSERT INTO eightvalues_question
                (quiz_index, question_text, effect_econ, effect_dipl, effect_govt, effect_scty)
            VALUES (%s, %s, %s, %s, %s, %s)
            ON CONFLICT (quiz_index) DO UPDATE SET
                question_text = EXCLUDED.question_text,
                effect_econ = EXCLUDED.effect_econ,
                effect_dipl = EXCLUDED.effect_dipl,
                effect_govt = EXCLUDED.effect_govt,
                effect_scty = EXCLUDED.effect_scty
            """,
            (idx, item["question"],
             int(eff.get("econ", 0)), int(eff.get("dipl", 0)),
             int(eff.get("govt", 0)), int(eff.get("scty", 0))),
        )
    return len(questions)


def seed_probe_statements(cur):
    """Seed for/against probe statements from config/eightvalues_probe_statements.json.

    Expected JSON: a list aligned to quiz_index, each {"for": "...", "against": "..."}
    (entries may be empty/absent until authored). Returns count seeded.
    """
    if not os.path.exists(PROBE_PATH):
        return 0
    with open(PROBE_PATH, "r", encoding="utf-8") as f:
        probes = json.load(f)
    seeded = 0
    for idx, item in enumerate(probes or []):
        cur.execute("SELECT id FROM eightvalues_question WHERE quiz_index = %s", (idx,))
        row = cur.fetchone()
        if not row:
            continue
        qid = row[0]
        for direction in ("for", "against"):
            text = (item or {}).get(direction)
            if not text:
                continue
            cur.execute(
                """
                INSERT INTO eightvalues_probe_statement (question_id, direction, statement_text)
                VALUES (%s, %s, %s)
                ON CONFLICT (question_id, direction) DO UPDATE SET statement_text = EXCLUDED.statement_text
                """,
                (qid, direction, text),
            )
            seeded += 1
    return seeded


def main():
    parser = argparse.ArgumentParser(description="Create + seed 8values tables on the main DB.")
    parser.add_argument("--drop", action="store_true", help="DROP and recreate (destroys 8values data)")
    parser.add_argument("--no-seed", action="store_true", help="Create tables only; skip seeding reference data")
    args = parser.parse_args()

    conn = psycopg2.connect(**load_db_config())
    try:
        with conn.cursor() as cur:
            if args.drop:
                cur.execute(DROP)
                print("Dropped existing 8values tables.")
            cur.execute(DDL)
        conn.commit()
        print("8values tables ready.")

        if not args.no_seed:
            with conn.cursor() as cur:
                seed_answer_options(cur)
                nq = seed_questions(cur)
                npb = seed_probe_statements(cur)
            conn.commit()
            print(f"Seeded {len(ANSWER_OPTIONS)} answer options, {nq} questions, {npb} probe statement(s).")
            if npb == 0:
                print("No probe statements seeded yet -- author config/eightvalues_probe_statements.json "
                      "(or run generate_probe_statements.py) then re-run.")
    finally:
        conn.close()


if __name__ == "__main__":
    main()
