-- =============================================================================
-- schema.sql  --  Full database schema for the transcript-analysis pipeline.
--
-- This recreates the LIVE schema (as captured by inspect_schema.py): integer
-- surrogate ids, yt_* external keys, model_id-keyed scores, the island tables,
-- and all observed indexes/constraints -- PLUS the new
-- idx_vid_transcript_vid_wc index that the scoring pipeline needs.
--
-- Safe to run on an empty database (everything is IF NOT EXISTS). It does NOT
-- drop anything; to rebuild from scratch, uncomment the DROP block below first.
--
-- Notes:
--   * Indexes here are created normally (fast on an empty DB). To add an index
--     to an already-populated table without locking it, use
--     CREATE INDEX CONCURRENTLY ... in a standalone statement instead.
--   * Surrogate keys use GENERATED BY DEFAULT AS IDENTITY so the app can let the
--     DB assign ids, while bulk migrations can still insert explicit ids.
--   * Run with DBeaver (whole script) or:  psql "$CONN" -f sql/schema.sql
-- =============================================================================

-- ---- OPTIONAL clean rebuild (DESTROYS DATA) -- uncomment to use --------------
-- DROP TABLE IF EXISTS island_task_table   CASCADE;
-- DROP TABLE IF EXISTS island_table        CASCADE;
-- DROP TABLE IF EXISTS vid_score_table      CASCADE;
-- DROP TABLE IF EXISTS vid_transcript_table CASCADE;
-- DROP TABLE IF EXISTS vid_data_table       CASCADE;
-- DROP TABLE IF EXISTS model_table          CASCADE;
-- DROP TABLE IF EXISTS vid_table            CASCADE;
-- DROP TABLE IF EXISTS channel_table        CASCADE;

BEGIN;

-- ---- channels ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS channel_table (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    yt_channel_id   VARCHAR(255),
    channel_handle  VARCHAR(255),
    channel_snippet JSON,
    insert_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_channel_table_yt_unique
    ON channel_table (yt_channel_id);

-- ---- videos -----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS vid_table (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id  BIGINT,
    yt_vid_id   VARCHAR(255),
    insert_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vid_channel FOREIGN KEY (channel_id) REFERENCES channel_table (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_vid_table_yt_unique
    ON vid_table (yt_vid_id);

-- ---- video metadata ("info") ------------------------------------------------
CREATE TABLE IF NOT EXISTS vid_data_table (
    vid_id      BIGINT,
    title       VARCHAR(255),
    description TEXT,
    publishtime TIMESTAMP,
    snippet     JSON,
    insert_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vid_data_table_vid FOREIGN KEY (vid_id) REFERENCES vid_table (id)
);

-- ---- transcripts ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS vid_transcript_table (
    vid_id         BIGINT,
    text           TEXT,
    start          DOUBLE PRECISION,
    duration       DOUBLE PRECISION,
    text_formatted TEXT,
    word_count     INTEGER,
    cum_word_count INTEGER,
    insert_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vid_transcript_table_vid FOREIGN KEY (vid_id) REFERENCES vid_table (id)
);
-- Critical for the scoring pipeline: pending-video lookups and transcript
-- fetches both filter on vid_id (+ word_count). Without this the 45M-row table
-- gets sequentially scanned on every call.
CREATE INDEX IF NOT EXISTS idx_vid_transcript_vid_wc
    ON vid_transcript_table (vid_id, word_count);

-- ---- models -----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS model_table (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    yt_model_key VARCHAR(255),
    model_data   BYTEA,
    insert_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_model_table_yt_unique
    ON model_table (yt_model_key);
-- Non-unique lookup index also present on the live DB (redundant with the
-- unique index above, but kept for parity).
CREATE INDEX IF NOT EXISTS idx_model_model_key
    ON model_table (yt_model_key);

-- ---- scores -----------------------------------------------------------------
-- One row per (vid_id, model_id); score is the per-word score array.
-- NOTE: there is intentionally only a NON-unique index on (vid_id, model_id)
-- (matching the live DB). The scoring client inserts only pairs that lack a
-- score, so it never needs an upsert. If you later want to enforce one row per
-- pair, first check for dupes, then add a UNIQUE index.
CREATE TABLE IF NOT EXISTS vid_score_table (
    vid_id    BIGINT,
    model_id  BIGINT,
    score     DOUBLE PRECISION[],
    insert_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vid_score_table_vid FOREIGN KEY (vid_id)   REFERENCES vid_table (id),
    CONSTRAINT fk_vid_score_model     FOREIGN KEY (model_id) REFERENCES model_table (id)
);
CREATE INDEX IF NOT EXISTS idx_vid_score_vid_model
    ON vid_score_table (vid_id, model_id);

-- ---- islands ----------------------------------------------------------------
-- Per-model islands of consecutive high-scoring words (start_index/end_index
-- are positions in that model's smoothed score sequence).
CREATE TABLE IF NOT EXISTS island_table (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vid_id      BIGINT NOT NULL,
    model_id    BIGINT NOT NULL,
    start_index INTEGER NOT NULL,
    end_index   INTEGER NOT NULL,
    insert_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT island_table_vid_fkey   FOREIGN KEY (vid_id)   REFERENCES vid_table (id),
    CONSTRAINT island_table_model_fkey FOREIGN KEY (model_id) REFERENCES model_table (id),
    CONSTRAINT island_table_range_chk  CHECK (start_index <= end_index),
    CONSTRAINT island_table_unique     UNIQUE (vid_id, model_id, start_index, end_index)
);
CREATE INDEX IF NOT EXISTS idx_island_vid_id    ON island_table (vid_id);
CREATE INDEX IF NOT EXISTS idx_island_model_id  ON island_table (model_id);
CREATE INDEX IF NOT EXISTS idx_island_vid_model ON island_table (vid_id, model_id);

-- ---- island work queue ------------------------------------------------------
-- One row per (vid_id, model_id) to score for islands; status drives the
-- DB-coordinated island workers (pending -> in_progress -> done/error).
CREATE TABLE IF NOT EXISTS island_task_table (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vid_id     BIGINT NOT NULL,
    model_id   BIGINT NOT NULL,
    status     VARCHAR(12) NOT NULL DEFAULT 'pending',
    attempts   INTEGER NOT NULL DEFAULT 0,
    error      TEXT,
    claimed_at TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    insert_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT island_task_table_vid_fkey   FOREIGN KEY (vid_id)   REFERENCES vid_table (id),
    CONSTRAINT island_task_table_model_fkey FOREIGN KEY (model_id) REFERENCES model_table (id),
    CONSTRAINT island_task_table_unique     UNIQUE (vid_id, model_id)
);
CREATE INDEX IF NOT EXISTS idx_island_task_status    ON island_task_table (status);
CREATE INDEX IF NOT EXISTS idx_island_task_vid_model ON island_task_table (vid_id, model_id);

COMMIT;
